FROM python:3.12-slim

WORKDIR /app

RUN pip install uv

COPY app/requirements.txt .
RUN uv pip install -r requirements.txt --system

COPY app/ .

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
